### ISSUE TITLE
error creating first applucation: Unhandled 'error' event

### ISSUE THREAD

**Issue by ruud** [jonparrott/Generator-Ferris-3#1]
yo ferris3

     _-----_
    |       |    .--------------------------.
    |--(o)--|    | Welcome to the marvelous |
   `---------´   |    Ferris3 generator!    |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What is your cloud project id? (ex, lofty-seer-632). my-project
? What is your client's OAuth2 client id? (optional) 
   create app/__init__.py
   create app/basic/__init__.py
   create app/basic/basic_handler.py
   create app/basic/basic_service.py
   create app/default-endpoint.yaml
   create app/settings.py
identical app/default-endpoint.yaml
   create app.yaml
   create requirements.txt
   create appengine_config.py
   create vendor.py
   create main.py

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by SpainTrain** [comment]
Looks like this issue can be closed
